# .github/workflows/version.yml
name: Git Version

on: [push, workflow_dispatch]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0                # fetch the whole repo history

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.5.0'

      - name: Determine GitVersion
        id: version
        uses: gittools/actions/gitversion/execute@v0.9.7

      - name: Display Version
        run: echo "${{ toJson(steps.version.outputs)  }}"